[workspace]
members = [
    "crates/processor",
    "crates/wasm",
]
resolver = "3"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }

cast_sign_loss = "allow"
cast_possible_truncation = "allow"
cast_precision_loss = "allow"

[profile.dev]
opt-level = 0
debug = 0
codegen-units = 256
incremental = true
panic = "abort"

[profile.bench]
debug = true

[profile.dev.build-override]
opt-level = 3

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
debug = false
strip = true
panic = "abort"
